[package]
name = "meee"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
minifb = "0.24"
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
futures = "0.3"
winapi = "0.3.9"
